import RNHTMLToPDF from 'react-native-html-to-pdf';
import AsyncStorage from '@react-native-async-storage/async-storage';

interface ExportOptions {
  fileName?: string;
  directory?: string;
  base64?: boolean;
}

/**
 * Export data to HTML format for PDF generation
 */
export const exportToHTML = async (
  content: string,
  fileName: string,
  options: ExportOptions = {}
): Promise<string | null> => {
  try {
    const { directory = '', base64 = false, fileName: customFileName = fileName } = options;

    const optionsHTML: any = {
      html: content,
      fileName: customFileName,
      directory: directory || 'Documents',
      base64: base64,
      font: {
        size: 12,
        family: 'Arial',
      },
      header: {
        height: '11mm',
        contents: '<div style="font-size: 10px; text-align: center;">HR Manager - ' + new Date().toLocaleDateString() + '</div>',
      },
      footer: {
        height: '10mm',
        contents: '<div style="font-size: 10px; text-align: center;">Generated by HR Manager App</div>',
      },
      format: 'A4',
      orientation: 'portrait',
    };

    const file: any = await RNHTMLToPDF.convert(optionsHTML);

    if (base64) {
      return file.base64;
    }

    return file.path;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return null;
  }
};

/**
 * Generate payslip HTML content
 */
export const generatePayslipHTML = (data: any): string => {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    .header { text-align: center; margin-bottom: 30px; }
    .title { font-size: 24px; font-weight: bold; }
    .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 30px; }
    .info-item { margin-bottom: 10px; }
    .info-label { font-weight: bold; color: #333; }
    .info-value { margin-left: 10px; }
    .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    .table th { background-color: #3F51B5; color: white; padding: 12px; text-align: left; }
    .table td { padding: 10px; border-bottom: 1px solid #ddd; }
    .table .amount { text-align: right; font-weight: bold; }
    .totals { text-align: right; margin-top: 20px; }
    .total-row { font-size: 18px; font-weight: bold; padding: 10px; }
    .signature { text-align: center; margin-top: 50px; }
    .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">EMPLOYEE PAYSLIP</div>
    <div class="subtitle">Pay Period: ${data.payPeriod} | ${data.fiscalYear}</div>
  </div>

  <div class="info-grid">
    <div class="info-item">
      <span class="info-label">Employee Name:</span>
      <span class="info-value">${data.employeeName}</span>
    </div>
    <div class="info-item">
      <span class="info-label">Employee ID:</span>
      <span class="info-value">${data.employeeId}</span>
    </div>
    <div class="info-item">
      <span class="info-label">Department:</span>
      <span class="info-value">${data.department}</span>
    </div>
    <div class="info-item">
      <span class="info-label">Designation:</span>
      <span class="info-value">${data.designation}</span>
    </div>
    <div class="info-item">
      <span class="info-label">Pay Date:</span>
      <span class="info-value">${data.payDate}</span>
    </div>
    <div class="info-item">
      <span class="info-label">Bank Account:</span>
      <span class="info-value">${data.bankAccount}</span>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Earnings</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${data.earnings.map((earn: any) => `
        <tr>
          <td>${earn.name}</td>
          <td class="amount">${earn.amount.toFixed(2)}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th>Deductions</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${data.deductions.map((ded: any) => `
        <tr>
          <td>${ded.name}</td>
          <td class="amount">-${ded.amount.toFixed(2)}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="totals">
    <div class="total-row">Gross Salary: ${data.grossSalary.toFixed(2)}</div>
    <div class="total-row">Total Deductions: ${data.totalDeductions.toFixed(2)}</div>
    <div class="total-row" style="color: #3F51B5;">Net Salary: ${data.netSalary.toFixed(2)}</div>
  </div>

  <div class="signature">
    <p>Employee Signature: _____________________</p>
    <p>Date: ${new Date().toLocaleDateString()}</p>
  </div>

  <div class="footer">
    <p>This is a computer-generated payslip and does not require a physical signature.</p>
    <p>HR Manager App - www.hrmanger.com</p>
  </div>
</body>
</html>
  `.trim();
};

/**
 * Generate report HTML content
 */
export const generateReportHTML = (data: any): string => {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    .header { text-align: center; margin-bottom: 30px; }
    .title { font-size: 24px; font-weight: bold; }
    .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
    .filters { background-color: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
    .filters-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin-top: 10px; }
    .filter-item label { display: block; font-weight: bold; margin-bottom: 5px; }
    .filter-item select { width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; }
    .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    .table th { background-color: #3F51B5; color: white; padding: 12px; text-align: left; }
    .table td { padding: 10px; border-bottom: 1px solid #ddd; }
    .summary { text-align: right; margin-top: 20px; }
    .summary-row { font-size: 14px; padding: 8px; }
    .summary-total { font-size: 18px; font-weight: bold; padding: 10px; }
    .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">${data.title}</div>
    <div class="subtitle">Period: ${data.period} | Generated: ${new Date().toLocaleDateString()}</div>
  </div>

  <div class="filters">
    <div class="filters-grid">
      <div class="filter-item">
        <label>Department</label>
        <select>${data.departmentFilter}</select>
      </div>
      <div class="filter-item">
        <label>Month</label>
        <select>${data.monthFilter}</select>
      </div>
      <div class="filter-item">
        <label>Year</label>
        <select>${data.yearFilter}</select>
      </div>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Department</th>
        <th>${data.column1}</th>
        <th>${data.column2}</th>
        <th>${data.column3}</th>
        <th>${data.column4}</th>
      </tr>
    </thead>
    <tbody>
      ${data.rows.map((row: any) => `
        <tr>
          <td>${row.id}</td>
          <td>${row.name}</td>
          <td>${row.department}</td>
          <td>${row.value1}</td>
          <td>${row.value2}</td>
          <td>${row.value3}</td>
          <td>${row.value4}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="summary">
    <div class="summary-row">Total Records: ${data.totalRecords}</div>
    <div class="summary-total">Total: ${data.totalValue}</div>
  </div>

  <div class="footer">
    <p>Generated by HR Manager App</p>
  </div>
</body>
</html>
  `.trim();
};

export default {
  exportToHTML,
  generatePayslipHTML,
  generateReportHTML,
};